package com.ems.dto;

import java.util.List;

import com.ems.entity.Employee;
import com.ems.entity.Finance;
import com.ems.entity.ProfessionalDetails;
import com.ems.entity.Project;

import lombok.Data;

@Data
public class EmployeeDTO {
	
    private Employee employee;
    private ProfessionalDetails professionalDetails;
    private List<Project> projectDetails;
    private Finance financeDetails;
    
//    public Employee getPersonalDetails(Employee employee) {
//    	personalDetails.setEmployee(employee);
//    	return personalDetails;
//    }
 // Getter for personalDetails
    public Employee getPersonalDetails() {
        return employee;
    }

    // Setter for personalDetails (optional, if not already generated by Lombok)
    public void setPersonalDetails(Employee employee) {
        this.employee = employee;
    }

    public ProfessionalDetails getProfessionalDetails(Employee employee) {
        professionalDetails.setEmployee(employee);
        return professionalDetails;
    }
    public Finance getFinanceDetails(Employee employee) {
        financeDetails.setEmployee(employee);
        return financeDetails;
    }
    
//    public List<Project> getProjectDetails(Employee employee) {
//        ((Iterable<Project>) projectDetails).forEach(project -> project.setEmployee(employee));
//        return (List<Project>) projectDetails;
//    }
    	public List<Project> getProjectDetails(Employee employee) {
        if (projectDetails != null) {
            projectDetails.forEach(project -> project.setEmployee(employee));
        }
        return projectDetails;
    }

//	    public Project getProjectDetails(Employee employee) {
//	        projectDetails.forEach(project -> project.setEmployee(employee));
//	        return projectDetails;
//	    }
   
//
    
}

